version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  auth-postgres:
    image: postgres:15
    container_name: auth-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: authdb
    ports:
      - "55632:5432"
    volumes:
      - auth_pgdata:/var/lib/postgresql/data

  authservice-api:
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    container_name: authservice-api
    depends_on:
      - auth-postgres
      - rabbitmq
    ports:
      - "5601:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=auth-postgres;Port=5432;Database=authdb;Username=admin;Password=admin123

  users-postgres:
    image: postgres:15
    container_name: users-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: usersdb
    ports:
      - "55732:5432"
    volumes:
      - users_pgdata:/var/lib/postgresql/data

  userservice-api:
    build:
      context: .
      dockerfile: UserService/Dockerfile
    container_name: userservice-api
    depends_on:
      - users-postgres
      - rabbitmq
    ports:
      - "5602:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=users-postgres;Port=5432;Database=usersdb;Username=admin;Password=admin123

  topic-postgres:
    image: postgres:15
    container_name: topic-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: topicsdb
    ports:
      - "55932:5432"
    volumes:
      - topic_pgdata:/var/lib/postgresql/data

  topicservice-api:
    build:
      context: .
      dockerfile: TopicService/Dockerfile
    container_name: topicservice-api
    depends_on:
      - topic-postgres
      - rabbitmq
    ports:
      - "5603:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=topic-postgres;Port=5432;Database=topicsdb;Username=admin;Password=admin123

volumes:
  auth_pgdata:
  users_pgdata:
  topic_pgdata:

