version: '3.8'

services:
  auth-postgres:
    image: postgres:15
    container_name: auth-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: authdb
    ports:
      - "55632:5432"
    volumes:
      - auth_pgdata:/var/lib/postgresql/data

  authservice-api:
    build:
      context: .
      dockerfile: /AuthService/Dockerfile
    container_name: authservice-api
    depends_on:
      - auth-postgres
    ports:
      - "5601:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=auth-postgres;Port=5432;Database=authdb;Username=admin;Password=admin123

volumes:
  auth_pgdata:
